name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake (Dark Mode)
        uses: Platane/snk@v3
        with:
          github_user_name: MdFawazAli
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
          # Customize colors
          color_snake: "#00FF00"
          color_dots: "#444", "#666", "#888", "#AAA", "#CCC"
          background: "transparent"  # You can also try "#000000" for black
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
